// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: rpccall/baseapi/oscall/os.proto

package oscall

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	FileMode uint32 `protobuf:"varint,2,opt,name=FileMode,proto3" json:"FileMode,omitempty"`
}

func (x *Dir) Reset() {
	*x = Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir) ProtoMessage() {}

func (x *Dir) ProtoReflect() protoreflect.Message {
	mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir.ProtoReflect.Descriptor instead.
func (*Dir) Descriptor() ([]byte, []int) {
	return file_rpccall_baseapi_oscall_os_proto_rawDescGZIP(), []int{0}
}

func (x *Dir) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dir) GetFileMode() uint32 {
	if x != nil {
		return x.FileMode
	}
	return 0
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_rpccall_baseapi_oscall_os_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FileWithContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File    *File  `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *FileWithContent) Reset() {
	*x = FileWithContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileWithContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWithContent) ProtoMessage() {}

func (x *FileWithContent) ProtoReflect() protoreflect.Message {
	mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWithContent.ProtoReflect.Descriptor instead.
func (*FileWithContent) Descriptor() ([]byte, []int) {
	return file_rpccall_baseapi_oscall_os_proto_rawDescGZIP(), []int{2}
}

func (x *FileWithContent) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileWithContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FilesToCopy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*File `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
	Dir   string  `protobuf:"bytes,2,opt,name=Dir,proto3" json:"Dir,omitempty"`
}

func (x *FilesToCopy) Reset() {
	*x = FilesToCopy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilesToCopy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesToCopy) ProtoMessage() {}

func (x *FilesToCopy) ProtoReflect() protoreflect.Message {
	mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesToCopy.ProtoReflect.Descriptor instead.
func (*FilesToCopy) Descriptor() ([]byte, []int) {
	return file_rpccall_baseapi_oscall_os_proto_rawDescGZIP(), []int{3}
}

func (x *FilesToCopy) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FilesToCopy) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type FilesToDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*File `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
}

func (x *FilesToDelete) Reset() {
	*x = FilesToDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilesToDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesToDelete) ProtoMessage() {}

func (x *FilesToDelete) ProtoReflect() protoreflect.Message {
	mi := &file_rpccall_baseapi_oscall_os_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesToDelete.ProtoReflect.Descriptor instead.
func (*FilesToDelete) Descriptor() ([]byte, []int) {
	return file_rpccall_baseapi_oscall_os_proto_rawDescGZIP(), []int{4}
}

func (x *FilesToDelete) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_rpccall_baseapi_oscall_os_proto protoreflect.FileDescriptor

var file_rpccall_baseapi_oscall_os_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x70, 0x63, 0x63, 0x61, 0x6c, 0x6c, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x61, 0x70,
	0x69, 0x2f, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x2f, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x6f, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x35, 0x0a, 0x03, 0x44, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x3f, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x54, 0x6f, 0x43, 0x6f, 0x70, 0x79, 0x12,
	0x1e, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x44, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x69,
	0x72, 0x22, 0x2f, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x54, 0x6f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x32, 0xd6, 0x01, 0x0a, 0x06, 0x4f, 0x53, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x28, 0x0a,
	0x05, 0x4d, 0x6b, 0x64, 0x69, 0x72, 0x12, 0x07, 0x2e, 0x6f, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x07, 0x43, 0x50, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x12, 0x0f, 0x2e, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x54, 0x6f, 0x43,
	0x6f, 0x70, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x09, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x6f, 0x73, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x34, 0x0a, 0x07, 0x52, 0x4d, 0x46, 0x69, 0x6c, 0x65, 0x73,
	0x12, 0x11, 0x2e, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x54, 0x6f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x62, 0x61, 0x62,
	0x61, 0x2f, 0x73, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x63, 0x61, 0x6c, 0x6c,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpccall_baseapi_oscall_os_proto_rawDescOnce sync.Once
	file_rpccall_baseapi_oscall_os_proto_rawDescData = file_rpccall_baseapi_oscall_os_proto_rawDesc
)

func file_rpccall_baseapi_oscall_os_proto_rawDescGZIP() []byte {
	file_rpccall_baseapi_oscall_os_proto_rawDescOnce.Do(func() {
		file_rpccall_baseapi_oscall_os_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpccall_baseapi_oscall_os_proto_rawDescData)
	})
	return file_rpccall_baseapi_oscall_os_proto_rawDescData
}

var file_rpccall_baseapi_oscall_os_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpccall_baseapi_oscall_os_proto_goTypes = []interface{}{
	(*Dir)(nil),             // 0: os.Dir
	(*File)(nil),            // 1: os.File
	(*FileWithContent)(nil), // 2: os.FileWithContent
	(*FilesToCopy)(nil),     // 3: os.FilesToCopy
	(*FilesToDelete)(nil),   // 4: os.FilesToDelete
	(*emptypb.Empty)(nil),   // 5: google.protobuf.Empty
}
var file_rpccall_baseapi_oscall_os_proto_depIdxs = []int32{
	1, // 0: os.FileWithContent.File:type_name -> os.File
	1, // 1: os.FilesToCopy.Files:type_name -> os.File
	1, // 2: os.FilesToDelete.Files:type_name -> os.File
	0, // 3: os.OSCall.Mkdir:input_type -> os.Dir
	3, // 4: os.OSCall.CPFiles:input_type -> os.FilesToCopy
	2, // 5: os.OSCall.WriteFile:input_type -> os.FileWithContent
	4, // 6: os.OSCall.RMFiles:input_type -> os.FilesToDelete
	5, // 7: os.OSCall.Mkdir:output_type -> google.protobuf.Empty
	5, // 8: os.OSCall.CPFiles:output_type -> google.protobuf.Empty
	5, // 9: os.OSCall.WriteFile:output_type -> google.protobuf.Empty
	5, // 10: os.OSCall.RMFiles:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpccall_baseapi_oscall_os_proto_init() }
func file_rpccall_baseapi_oscall_os_proto_init() {
	if File_rpccall_baseapi_oscall_os_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpccall_baseapi_oscall_os_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpccall_baseapi_oscall_os_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpccall_baseapi_oscall_os_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileWithContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpccall_baseapi_oscall_os_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilesToCopy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpccall_baseapi_oscall_os_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilesToDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpccall_baseapi_oscall_os_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpccall_baseapi_oscall_os_proto_goTypes,
		DependencyIndexes: file_rpccall_baseapi_oscall_os_proto_depIdxs,
		MessageInfos:      file_rpccall_baseapi_oscall_os_proto_msgTypes,
	}.Build()
	File_rpccall_baseapi_oscall_os_proto = out.File
	file_rpccall_baseapi_oscall_os_proto_rawDesc = nil
	file_rpccall_baseapi_oscall_os_proto_goTypes = nil
	file_rpccall_baseapi_oscall_os_proto_depIdxs = nil
}
